### ISSUE TITLE
Choco3 native support -- Maven dependency

### ISSUE THREAD

**Issue by cprudhom** [cp-profiler/java-integration#1]
I created the required class in Choco3 (develop branch).
It works (almost) like a charm (the application sometimes craches) but I did not published the code yet because it requires this project as a dependency, and I'm looking for clean way to declare it.
Do you plan to publish this library on Maven Central Repository ?
This would really be nice of you.

**Comment by msgmaxim** [comment]
Sounds good! We will publish it there then. It might take a couple of days to get through, so I will let you know when it is available there. Thanks!

**Comment by msgmaxim** [comment]
I've deployed the module to the Maven Central:

``` Java
<dependency>
    <groupId>com.github.cp-profiler</groupId>
    <artifactId>cpprof-java</artifactId>
    <version>1.0.0</version>
</dependency>
```

Note that I allowed myself to change the API slightly to follow the corresponding C++ version of the library, and also augmented the API to allow parameter specification using chaining syntax (that is to support optional fields). I don't expect any more backwards incompatible changes in the future.

You may find useful the example I've just added on how to use the integration module (it uses the Maven package, minimal and works): https://github.com/cp-profiler/java-integration-example.

**Comment by cprudhom** [comment]
Thanks. I add a search monitor (see https://github.com/chocoteam/choco3/issues/341, currently in the develop branch). But when I try to use it, cp-profiler crashes. I don't know if where to find log files to help me/you fixing the issue.

**Comment by msgmaxim** [comment]
I noticed that you don't send `BRANCH` nodes. Should they be sent in `beforeDownBranch()` method when branching left?

**Comment by cprudhom** [comment]
You're right, I missed that point. That works like a charm now.
